### ISSUE TITLE
Separator / resize grip between menu bar and search bar is not styled

### ISSUE THREAD

**Issue by ohnonot** [alice-mkh/gnomerunner#13]
Hello,
thanks for maintaining this.
I'm running seamonkey 2.49.1 on ArchLinux.
After a long overdue update from 2.46 (where i already used this addon without issues), I am now seeing a strange white vertical 1px line between the menu bar and the search bar. It is actually a separator grip, and only appears when there's (too) many elements on the bar.

I have put most UI elements on the menu bar, the navigation bar is not enabled, to save space.

Here's a [screenshot][1] of the issue, and here's a [screenshot][2] of the default theme for comparison.

I tried tweaking userChrome.css to no avail:

    toolbarseparator { opacity: 0 !important; }

    #toolbar-menubar, menubar, toolbox, toolbar {
      border-style: none !important;
    }

Is there a way to fix this in the addon, or a tweak I can add to userChrome.css?
Fwiw, I don't need that grip at all, styled or not.

[1]: http://dt.iki.fi/stuff/seamonkey/seamonkey-gnomerunner.png
[2]: http://dt.iki.fi/stuff/seamonkey/seamonkey-default.png

**Comment by alice-mkh** [comment]
Hi! Fixed this in https://github.com/Exalm/gnomerunner/commit/58fcfc96bcfe8b2dcaa2f51063a7023ba00ef01e

**Comment by ohnonot** [comment]
Hello, how does this propagate to the addon installed from https://addons.mozilla.org/en-us/seamonkey/addon/gnomerunnergtk-revived/ ?

Because I am not seeing any change, nor any updates in addons-manager.

the CSS works fine though when i add it to userChrome.css, so thanks for that  :)

**Comment by alice-mkh** [comment]
Yes, I haven't released it yet. :)
